/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteRouteImport } from './routes/org/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as OrgMembersIndexRouteImport } from './routes/org/members/index'
import { Route as OrgDashboardIndexRouteImport } from './routes/org/dashboard/index'
import { Route as publicPricingIndexRouteImport } from './routes/(public)/pricing/index'
import { Route as publicLandingIndexRouteImport } from './routes/(public)/landing/index'
import { Route as publicAboutIndexRouteImport } from './routes/(public)/about/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrgMembersMemberIdRouteRouteImport } from './routes/org/members/$memberId/route'
import { Route as OrgMembersMemberIdIndexRouteImport } from './routes/org/members/$memberId/index'

const OrgRouteRoute = OrgRouteRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgMembersIndexRoute = OrgMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgDashboardIndexRoute = OrgDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => OrgRouteRoute,
} as any)
const publicPricingIndexRoute = publicPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLandingIndexRoute = publicLandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutIndexRoute = publicAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => publicRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgMembersMemberIdRouteRoute = OrgMembersMemberIdRouteRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgMembersMemberIdIndexRoute = OrgMembersMemberIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgMembersMemberIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/org': typeof OrgRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/': typeof publicIndexRoute
  '/org/members/$memberId': typeof OrgMembersMemberIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/about/': typeof publicAboutIndexRoute
  '/landing/': typeof publicLandingIndexRoute
  '/pricing/': typeof publicPricingIndexRoute
  '/org/dashboard/': typeof OrgDashboardIndexRoute
  '/org/members/': typeof OrgMembersIndexRoute
  '/org/members/$memberId/': typeof OrgMembersMemberIdIndexRoute
}
export interface FileRoutesByTo {
  '/org': typeof OrgRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/about': typeof publicAboutIndexRoute
  '/landing': typeof publicLandingIndexRoute
  '/pricing': typeof publicPricingIndexRoute
  '/org/dashboard': typeof OrgDashboardIndexRoute
  '/org/members': typeof OrgMembersIndexRoute
  '/org/members/$memberId': typeof OrgMembersMemberIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/org': typeof OrgRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(public)/': typeof publicIndexRoute
  '/org/members/$memberId': typeof OrgMembersMemberIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(public)/about/': typeof publicAboutIndexRoute
  '/(public)/landing/': typeof publicLandingIndexRoute
  '/(public)/pricing/': typeof publicPricingIndexRoute
  '/org/dashboard/': typeof OrgDashboardIndexRoute
  '/org/members/': typeof OrgMembersIndexRoute
  '/org/members/$memberId/': typeof OrgMembersMemberIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/org'
    | '/login'
    | '/'
    | '/org/members/$memberId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/about/'
    | '/landing/'
    | '/pricing/'
    | '/org/dashboard/'
    | '/org/members/'
    | '/org/members/$memberId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/org'
    | '/login'
    | '/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/about'
    | '/landing'
    | '/pricing'
    | '/org/dashboard'
    | '/org/members'
    | '/org/members/$memberId'
  id:
    | '__root__'
    | '/(public)'
    | '/org'
    | '/(auth)/login'
    | '/(public)/'
    | '/org/members/$memberId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/(public)/about/'
    | '/(public)/landing/'
    | '/(public)/pricing/'
    | '/org/dashboard/'
    | '/org/members/'
    | '/org/members/$memberId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  OrgRouteRoute: typeof OrgRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/members/': {
      id: '/org/members/'
      path: '/members'
      fullPath: '/org/members/'
      preLoaderRoute: typeof OrgMembersIndexRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/dashboard/': {
      id: '/org/dashboard/'
      path: '/dashboard'
      fullPath: '/org/dashboard/'
      preLoaderRoute: typeof OrgDashboardIndexRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/(public)/pricing/': {
      id: '/(public)/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof publicPricingIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/landing/': {
      id: '/(public)/landing/'
      path: '/landing'
      fullPath: '/landing/'
      preLoaderRoute: typeof publicLandingIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about/': {
      id: '/(public)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof publicAboutIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/members/$memberId': {
      id: '/org/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/org/members/$memberId'
      preLoaderRoute: typeof OrgMembersMemberIdRouteRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/org/members/$memberId/': {
      id: '/org/members/$memberId/'
      path: '/'
      fullPath: '/org/members/$memberId/'
      preLoaderRoute: typeof OrgMembersMemberIdIndexRouteImport
      parentRoute: typeof OrgMembersMemberIdRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicAboutIndexRoute: typeof publicAboutIndexRoute
  publicLandingIndexRoute: typeof publicLandingIndexRoute
  publicPricingIndexRoute: typeof publicPricingIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicAboutIndexRoute: publicAboutIndexRoute,
  publicLandingIndexRoute: publicLandingIndexRoute,
  publicPricingIndexRoute: publicPricingIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface OrgMembersMemberIdRouteRouteChildren {
  OrgMembersMemberIdIndexRoute: typeof OrgMembersMemberIdIndexRoute
}

const OrgMembersMemberIdRouteRouteChildren: OrgMembersMemberIdRouteRouteChildren =
  {
    OrgMembersMemberIdIndexRoute: OrgMembersMemberIdIndexRoute,
  }

const OrgMembersMemberIdRouteRouteWithChildren =
  OrgMembersMemberIdRouteRoute._addFileChildren(
    OrgMembersMemberIdRouteRouteChildren,
  )

interface OrgRouteRouteChildren {
  OrgMembersMemberIdRouteRoute: typeof OrgMembersMemberIdRouteRouteWithChildren
  OrgDashboardIndexRoute: typeof OrgDashboardIndexRoute
  OrgMembersIndexRoute: typeof OrgMembersIndexRoute
}

const OrgRouteRouteChildren: OrgRouteRouteChildren = {
  OrgMembersMemberIdRouteRoute: OrgMembersMemberIdRouteRouteWithChildren,
  OrgDashboardIndexRoute: OrgDashboardIndexRoute,
  OrgMembersIndexRoute: OrgMembersIndexRoute,
}

const OrgRouteRouteWithChildren = OrgRouteRoute._addFileChildren(
  OrgRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  OrgRouteRoute: OrgRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
